### ISSUE TITLE
Can't build golang package

### ISSUE THREAD

**Issue by sk9la** [replit/upm#115]
Hi,

When trying to build the package using go install, I have this error: `go: github.com/replit/upm/internal/statik: no matching versions for query "upgrade"`

This is what I do to build it:
1. `git clone https://github.com/replit/upm.git`
2. `cd upm`
3. `go mod tidy`
4. `go install -v ./cmd/upm`

This is where I get the error

Any ideas ?

**Comment by cdmistman** [comment]
the best way to build is with nix right now. there's some work planned to get upm in a better state (eg #123) but getting `go install` to work here isn't a priority
