### ISSUE TITLE
Exits with Status 9009

### ISSUE THREAD

**Issue by M4cs** [replit/upm#12]
Running on Windows 10 with Python3

Trying to run any upm commands that utilize poetry result in a 9009. I have installed it from Scoop.

Is there a way to get verbose output?

**Comment by raxod502** [comment]
The default output is maximally verbose currently. I assume you have verified that if you manually run the commands that are printed out by UPM, then they work correctly?

**Comment by M4cs** [comment]
yeah poetry is working fine on it's own

**Comment by raxod502** [comment]
Well, if `python3 -m poetry ...` works in the shell, unfortunately I don't know what might be wrong. When more development bandwidth is available, somebody can test on a Windows machine and see what's up.

**Comment by blast-hardcheese** [comment]
This should be resolved now as we just execute `poetry` via CLI, so presumably if you have `poetry` on your `%PATH%` you'll be good.

Thanks for the report!
