### ISSUE TITLE
Support for Rust Crates via Cargo

### ISSUE THREAD

**Issue by syrusakbary** [replit/upm#18]
After the announcement, I started researching how easy could be to support Rust packages (with Crates.io/cargo) in this project.

I think the integration should be in general trivial, but `cargo` requires to manually modify `Cargo.toml` in order to add or remove packages (as opposed to doing it via a specific CLI subcommand like in npm, poetry, ...).

Is there any good way to support this? Have someone else thought about this?

**Comment by bb010g** [comment]
[cargo-edit](https://github.com/killercup/cargo-edit) exists to solve this problem, and it does so very well.

**Comment by Daniel-Liu-c0deb0t** [comment]
Is anyone working on this right now? I'm down to work on an initial version.

**Comment by blast-hardcheese** [comment]
Closed in #77! Thanks for the report!
