### ISSUE TITLE
Repository export

### ISSUE THREAD

**Issue by Bebbolus** [replit/upm#20]
please support the chance to export a target repositori (i.e. NPM), to restore in other installation.

**Comment by raxod502** [comment]
Could you elaborate on what this means concretely?

**Comment by blast-hardcheese** [comment]
Defining a new specification file/archive file is outside the scope of UPM, though you can implement it on top of UPM with something like this:

```shell
$ cd from-dir
$ upm list --format json > ../direct-deps.json
$ cd ../to-dir
$ cat ../direct-deps.json | \
    jq -r 'map(.name + "@" + .spec)[]' | \
    xargs upm add --lang nodejs-yarn
```

where `from-dir` contains a `npm` project and `to-dir` aspires to be a `yarn` project. `upm list --format json` is very versatile!

Please feel free to open a new issue if you have further suggestions, thank you!
