### ISSUE TITLE
Backend api 'Remove' function signature

### ISSUE THREAD

**Issue by ghost** [replit/upm#38]
This is probably a generic golang question. The signature of 'Remove' field of a backend api is:

```
field Remove func(map[PkgName]bool)
```

All the bool values in the map passed are set to `true`. Why is this hook being passed a map instead of an array?

**Comment by blast-hardcheese** [comment]
An old question at this point but still relevant. I just recently learned the answer myself, so I'll reproduce it here:

```go
var pkgs map[PkgName]bool

if pkgs[foo] {
  // Do stuff
}
```

vs...

```go
var pkgs []PkgName

for _, name := range pkgs {
  if name == foo {
    // do stuff
    break
  }
}
```

Additionally, you may inclined (as I was) to use `nil` as the value in a map, like `map[PkgName]interface{}`, but Go also has default values for many builtin types. The default value for `bool` is `false`, so by setting all the values to `true` you can just `if pkgs[foo]` and rely on packages that aren't in there being `false`

Thanks!
