### ISSUE TITLE
support for poetry being installed via package manager

### ISSUE THREAD

**Issue by Dragonlord1005** [replit/upm#63]
There is an issue where upm won't use poetry if it was installed via a package manager, as far as I can tell it NEEDS to use a pip installation of it

**Comment by techpixel** [comment]
Poetry is installed by default. Why would you want to install it again?

**Comment by blast-hardcheese** [comment]
This should be resolved in #107 -- I believe this question was due to upm depending on poetry as a library instead of just crafting arguments to be passed to whatever `poetry` is on `$PATH`.

Thank you for the report, feel free to comment if this is still an issue 🙂
