### ISSUE TITLE
Repl unable to wake up

### ISSUE THREAD

**Issue by DaCuteRaccoon** [replit/upm#80]
https://github.com/replit/upm/blob/d09be079699659fd58bbdc34b967ecba11e316d6/README.md?plain=1#L3
When you go to [amasad.me/public/images/long.png](https://amasad.me/public/images/long.png), it says that the Repl is unable to wake up. Maybe you shouldn't use Replit to host your image, or since you own Replit, you could host it not in a repl.

**Comment by DaCuteRaccoon** [comment]
Anyways, the image doesn't load

**Comment by blast-hardcheese** [comment]
Image is back now, thanks for reaching out!
