### ISSUE TITLE
Doesn't work with Poetry binary installed directly

### ISSUE THREAD

**Issue by raxod502** [replit/upm#9]
On Manjaro Linux:

```
% upm -l python add numpy                                                             
--> python3 -m poetry init --no-interaction
/usr/bin/python3: No module named poetry
exit status 1
```

This is because when Poetry is installed via the system package manager, it isn't available as a Python module; you need to go through the executable `/usr/bin/poetry`.

**Comment by blast-hardcheese** [comment]
This was resolved in #107, thanks!
